steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(varkathayat.solution)'

- task: VSBuild@1
  inputs:
    solution: '$(varkathayat.solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(varkathayat.buildPlatform)'
    configuration: '$(varkathayat.buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(varkathayat.buildPlatform)'
    configuration: '$(varkathayat.buildConfiguration)'